export const HERITAGE_FESTIVALS = [
  {
    id: 'diwali',
    name: 'Diwali - The Festival of Lights',
    location: 'Pan-India',
    state: 'All States',
    region: 'Whole India',
    period: 'Ancient',
    category: 'Festivals',
    description: 'A major Hindu festival symbolizing the spiritual victory of light over darkness, good over evil, and knowledge over ignorance.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv2mLQbs4XBVvH2K_dDBY7O0aXYMLKzwgucfvCk7nEOw&s=10',
    featured: true,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Diwali',
    fullDescription: 'Diwali is one of the most popular festivals of Hinduism. It usually lasts five days and is celebrated during the Hindu lunisolar month Kartika. People illuminate their homes, temples, and workspaces with diyas (oil lamps), candles, and lanterns. It is also a major cultural event for the Sikh, Jain, and Buddhist communities.'
  },
  {
    id: 'holi',
    name: 'Holi - The Festival of Colors',
    location: 'Pan-India',
    state: 'All States (Prominent in North)',
    region: 'North & Central India',
    period: 'Ancient',
    category: 'Festivals',
    description: 'A vibrant spring festival celebrating love, color, and the arrival of spring, where people play with colored powders and water.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyiyOxy5L9M7bbfX7UmlTX-9GGVAc6wNkYVmM0CT7RLg&s=10',
    featured: true,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Holi',
    fullDescription: 'Holi is a popular ancient Hindu festival, also known as the Festival of Spring, the Festival of Colours or the Festival of Love. The festival signifies the arrival of spring, the end of winter, the blossoming of love, and for many it is a festive day to meet others, play and laugh, forget and forgive, and repair broken relationships.'
  },
  {
    id: 'durga-puja',
    name: 'Durga Puja',
    location: 'Kolkata',
    state: 'West Bengal',
    region: 'East India',
    period: 'Medieval/Modern',
    category: 'Festivals',
    description: 'An annual Hindu festival originating in the Indian subcontinent which reveres and pays homage to the Hindu goddess Durga.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDXzAqY78KsYxbRjW8VAbgfRrEsdpNEluqtJycrUMpTg&s=10',
    featured: true,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Durga_Puja',
    fullDescription: 'Durga Puja is particularly popular and traditionally celebrated in the Indian states of West Bengal, Bihar, Assam, Tripura, and Odisha. It is a ten-day festival, of which the last five are of most significance. The festival is marked by scripture recitations, performance arts, revelry, gift-giving, family visits, feasting, and public processions.'
  },
  {
    id: 'eid',
    name: 'Eid ul-Fitr',
    location: 'Pan-India',
    state: 'All States',
    region: 'Whole India',
    period: '7th Century CE',
    category: 'Festivals',
    description: 'A major religious holiday celebrated by Muslims worldwide that marks the end of the month-long dawn-to-sunset fasting of Ramadan.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7hmKtjTPRSwfbBw0ESrVWn6eG7is9OYRl8UqMZRHvYw&s=10',
    featured: false,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Eid_al-Fitr',
    fullDescription: 'Eid al-Fitr marks the end of Ramadan, the Islamic holy month of fasting. The holiday celebrates the conclusion of the 29 or 30 days of dawn-to-sunset fasting. In India, it is celebrated with great fervor, involving special prayers, sweet dishes like Sheer Khurma, new clothes, and giving charity (Zakat).'
  },
  {
    id: 'onam',
    name: 'Onam',
    location: 'Kerala',
    state: 'Kerala',
    region: 'South India',
    period: 'Ancient',
    category: 'Festivals',
    description: 'An annual harvest and cultural festival of Kerala, famous for snake boat races, tiger dances, and flower rangolis.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfvi5A0JQG-Th1NAcCm1JblGKFbVooM3sr7ioXU2rpsQ&s=10',
    featured: false,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Onam',
    fullDescription: 'Onam is an annual Indian harvest festival celebrated predominantly by the Hindus of Kerala. A major annual event for Keralites, it is the official festival of the state and includes a spectrum of cultural events such as Vallam Kali (boat races), Pulikali (tiger dances), Pookkalam (flower arrangement), and Onathappan (worship).'
  },
  {
    id: 'ganesh-chaturthi',
    name: 'Ganesh Chaturthi',
    location: 'Mumbai/Pune',
    state: 'Maharashtra',
    region: 'West India',
    period: 'Ancient/Modern Revival',
    category: 'Festivals',
    description: 'A ten-day Hindu festival celebrating the arrival of Lord Ganesha to earth with elaborate pandals and immersive street processions.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR__2bxtEB8DsDoKDeszo4fnQXyuPe9VSc9wZTfbxk9Tw&s=10',
    featured: true,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ganesh_Chaturthi',
    fullDescription: 'Ganesh Chaturthi is a Hindu festival celebrating the arrival of Lord Ganesha to earth from Kailash Parvat with his mother Goddess Parvati/Gauri. The festival is marked with the installation of Ganesha clay idols privately in homes and publicly on elaborate pandals. It concludes on the tenth day with the immersion of the idols in water bodies.'
  }
];
