export const STATE_DATA = [
  { id: 'JK', name: 'Jammu and Kashmir', top: '15%', left: '32%', fact: 'Paradise of ancient monasteries and Sufi shrines.' },
  { id: 'LA', name: 'Ladakh', top: '10%', left: '38%', fact: 'Land of high passes, ancient Tibetan Buddhist monasteries and rugged beauty.' },
  { id: 'HP', name: 'Himachal Pradesh', top: '18%', left: '35%', fact: 'Home to the Dalai Lama, colonial hill stations, and Himalayan temples.' },
  { id: 'PB', name: 'Punjab', top: '25%', left: '30%', fact: 'The land of the Golden Temple and rich agricultural heritage.' },
  { id: 'HR', name: 'Haryana', top: '28%', left: '32%', fact: 'Epicenter of the Mahabharata and cradle of ancient Vedic civilization.' },
  { id: 'DL', name: 'Delhi', top: '29%', left: '33%', fact: 'A historic metropolis adorned with Mughal monuments and colonial architecture.' },
  { id: 'UK', name: 'Uttarakhand', top: '22%', left: '38%', fact: 'The Land of Gods, famous for the Char Dham pilgrimage and yoga heritage.' },
  { id: 'RJ', name: 'Rajasthan', top: '40%', left: '20%', fact: 'A royal legacy of majestic forts and vibrant palaces.' },
  { id: 'GJ', name: 'Gujarat', top: '55%', left: '10%', fact: 'Home to the ancient Indus Valley sites and stepwells.' },
  { id: 'MH', name: 'Maharashtra', top: '65%', left: '25%', fact: 'The land of Maratha forts and the magnificent Ajanta-Ellora caves.' },
  { id: 'GA', name: 'Goa', top: '72%', left: '24%', fact: 'A beautiful blend of pristine beaches and centuries-old Portuguese churches.' },
  { id: 'KA', name: 'Karnataka', top: '78%', left: '30%', fact: 'Hampi’s ruins and exquisite Hoysala temple architecture.' },
  { id: 'KL', name: 'Kerala', top: '90%', left: '33%', fact: 'God’s own country, famous for ancient martial arts and backwaters.' },
  { id: 'TN', name: 'Tamil Nadu', top: '88%', left: '42%', fact: 'The cradle of monumental Dravidian temple architecture.' },
  { id: 'AP', name: 'Andhra Pradesh', top: '75%', left: '45%', fact: 'Rich in Buddhist heritage and the legacy of the Satavahanas.' },
  { id: 'TG', name: 'Telangana', top: '65%', left: '40%', fact: 'Home to the Kakatiya dynasty ruins and Charminar.' },
  { id: 'MP', name: 'Madhya Pradesh', top: '50%', left: '40%', fact: 'The heart of India, featuring Khajuraho and Sanchi Stupa.' },
  { id: 'CG', name: 'Chhattisgarh', top: '55%', left: '48%', fact: 'Known for its ancient tribal culture, waterfalls, and terracotta crafts.' },
  { id: 'UP', name: 'Uttar Pradesh', top: '35%', left: '50%', fact: 'The Taj Mahal, Varanasi ghats, and deep spiritual roots.' },
  { id: 'BR', name: 'Bihar', top: '38%', left: '65%', fact: 'The birthplace of Buddhism and the ancient Nalanda University.' },
  { id: 'JH', name: 'Jharkhand', top: '45%', left: '62%', fact: 'A land of rich forests, waterfalls, and vibrant tribal heritage.' },
  { id: 'WB', name: 'West Bengal', top: '48%', left: '72%', fact: 'Rich literary heritage and colonial-era architecture.' },
  { id: 'OR', name: 'Odisha', top: '55%', left: '60%', fact: 'The majestic Sun Temple of Konark and Jagannath Puri.' },
  { id: 'SK', name: 'Sikkim', top: '32%', left: '78%', fact: 'Gateway to the Himalayas, known for its serene Buddhist monasteries.' },
  { id: 'AS', name: 'Assam', top: '35%', left: '85%', fact: 'Ancient Ahom kingdom ruins and the Kamakhya Temple.' },
  { id: 'AR', name: 'Arunachal Pradesh', top: '28%', left: '92%', fact: 'The Land of Dawn-Lit Mountains, featuring the magnificent Tawang Monastery.' },
  { id: 'NL', name: 'Nagaland', top: '35%', left: '94%', fact: 'Home to fierce warrior tribes and the famous Hornbill Festival.' },
  { id: 'MN', name: 'Manipur', top: '42%', left: '93%', fact: 'Known for its classical dance forms and the unique Loktak Lake.' },
  { id: 'MZ', name: 'Mizoram', top: '48%', left: '90%', fact: 'A land of rolling hills, bamboo forests, and deep-rooted tribal culture.' },
  { id: 'TR', name: 'Tripura', top: '46%', left: '86%', fact: 'Famous for the Neermahal water palace and ancient rock carvings of Unakoti.' },
  { id: 'ML', name: 'Meghalaya', top: '40%', left: '84%', fact: 'The abode of clouds, famous for its incredible living root bridges.' }
];
